

package com.daphne.lazulite.wechat.entity;

import java.util.Date;

public class Member {

	private Integer id;

	private String wechatId;

	private String memberId;

	private String memberNumber;

	private String phonenum;

	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column we_member.update_time
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column we_member.name
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column we_member.shop_code
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	private String shopCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column we_member.is_active
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	private Integer isActive;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column we_member.inactive_date
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	private Date inactiveDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column we_member.we_membercol
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	private String weMembercol;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column we_member.channel_qrcode_id
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	private Integer channelQrcodeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column we_member.is_old_member
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	private Integer isOldMember;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column we_member.sex
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column we_member.birthday
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column we_member.points
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	private Integer points;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column we_member.id
	 * @return  the value of we_member.id
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column we_member.id
	 * @param id  the value for we_member.id
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column we_member.wechat_id
	 * @return  the value of we_member.wechat_id
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public String getWechatId() {
		return wechatId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column we_member.wechat_id
	 * @param wechatId  the value for we_member.wechat_id
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public void setWechatId(String wechatId) {
		this.wechatId = wechatId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column we_member.member_id
	 * @return  the value of we_member.member_id
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public String getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column we_member.member_id
	 * @param memberId  the value for we_member.member_id
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column we_member.member_number
	 * @return  the value of we_member.member_number
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public String getMemberNumber() {
		return memberNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column we_member.member_number
	 * @param memberNumber  the value for we_member.member_number
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public void setMemberNumber(String memberNumber) {
		this.memberNumber = memberNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column we_member.phoneNum
	 * @return  the value of we_member.phoneNum
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public String getPhonenum() {
		return phonenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column we_member.phoneNum
	 * @param phonenum  the value for we_member.phoneNum
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public void setPhonenum(String phonenum) {
		this.phonenum = phonenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column we_member.create_time
	 * @return  the value of we_member.create_time
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column we_member.create_time
	 * @param createTime  the value for we_member.create_time
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column we_member.update_time
	 * @return  the value of we_member.update_time
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column we_member.update_time
	 * @param updateTime  the value for we_member.update_time
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column we_member.name
	 * @return  the value of we_member.name
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column we_member.name
	 * @param name  the value for we_member.name
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column we_member.shop_code
	 * @return  the value of we_member.shop_code
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public String getShopCode() {
		return shopCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column we_member.shop_code
	 * @param shopCode  the value for we_member.shop_code
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public void setShopCode(String shopCode) {
		this.shopCode = shopCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column we_member.is_active
	 * @return  the value of we_member.is_active
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public Integer getIsActive() {
		return isActive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column we_member.is_active
	 * @param isActive  the value for we_member.is_active
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column we_member.inactive_date
	 * @return  the value of we_member.inactive_date
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public Date getInactiveDate() {
		return inactiveDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column we_member.inactive_date
	 * @param inactiveDate  the value for we_member.inactive_date
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public void setInactiveDate(Date inactiveDate) {
		this.inactiveDate = inactiveDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column we_member.we_membercol
	 * @return  the value of we_member.we_membercol
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public String getWeMembercol() {
		return weMembercol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column we_member.we_membercol
	 * @param weMembercol  the value for we_member.we_membercol
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public void setWeMembercol(String weMembercol) {
		this.weMembercol = weMembercol;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column we_member.channel_qrcode_id
	 * @return  the value of we_member.channel_qrcode_id
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public Integer getChannelQrcodeId() {
		return channelQrcodeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column we_member.channel_qrcode_id
	 * @param channelQrcodeId  the value for we_member.channel_qrcode_id
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public void setChannelQrcodeId(Integer channelQrcodeId) {
		this.channelQrcodeId = channelQrcodeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column we_member.is_old_member
	 * @return  the value of we_member.is_old_member
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public Integer getIsOldMember() {
		return isOldMember;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column we_member.is_old_member
	 * @param isOldMember  the value for we_member.is_old_member
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public void setIsOldMember(Integer isOldMember) {
		this.isOldMember = isOldMember;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column we_member.sex
	 * @return  the value of we_member.sex
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column we_member.sex
	 * @param sex  the value for we_member.sex
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column we_member.birthday
	 * @return  the value of we_member.birthday
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column we_member.birthday
	 * @param birthday  the value for we_member.birthday
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column we_member.points
	 * @return  the value of we_member.points
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public Integer getPoints() {
		return points;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column we_member.points
	 * @param points  the value for we_member.points
	 * @mbggenerated  Mon Aug 10 11:19:03 CST 2015
	 */
	public void setPoints(Integer points) {
		this.points = points;
	}
}